#!/bin/bash

# Uncomment to debug
# set -x

jsTestRunnerPath="$(dirname ${0})/js/run-js-tests"
bashTestRunnerPath="$(dirname ${0})/bash/run-bash-tests"
cTestRunnerPath="$(dirname ${0})/c/run-c-tests"
phpTestRunnerPath="$(dirname ${0})/php/run-php-tests"

echo "Testing JavaScript scripts..." \
    && "${jsTestRunnerPath}" \
    && echo "All JavaScript tests PASSED" \
    || echo "Some JavaScript tests FAILED"

echo

echo "Testing Bash scripts..." \
    && "${bashTestRunnerPath}" \
    && echo "All Bash tests PASSED" \
    || echo "Some Bash tests FAILED"

echo

echo "Testing C implementations..." \
    && "${cTestRunnerPath}" \
    && echo "All C tests PASSED" \
    || echo "EITHER some C tests failed OR an error happened"

echo

echo "Testing PHP scripts..." \
    && "${phpTestRunnerPath}" \
    && echo "All PHP tests PASSED" \
    || echo "EITHER some PHP tests failed OR an error happened"
